name: "Initial Deployment Setup"

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: "the application name"
        required: true

env:
  BASE_PATH: ${{ vars.BASE_PATH }}

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: start ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: add host key
        run: ssh-keyscan -H -t rsa "${{ secrets.INSTANCE_HOST }}" >> ~/.ssh/known_hosts

      - name: check if app exists
        env:
          APP_NAME: ${{ inputs.app_name }}
        run: |
          ssh "${{ secrets.INSTANCE_USER }}@${{ secrets.INSTANCE_HOST }}" "bash -s" <<EOF
          set -euo pipefail
          BASE_PATH="${BASE_PATH:-}"
          APP_NAME="${APP_NAME:-}"
          if [ -z "${APP_NAME}" ]; then
            echo "APP_NAME is empty. Stopping setup."
            exit 1
          fi
          if [ -z "${BASE_PATH}" ]; then
            echo "BASE_PATH is empty. Stopping setup."
            exit 1
          fi
          TARGET="${BASE_PATH}/${APP_NAME}"
          echo "Checking ${TARGET}"
          if [ -d "${TARGET}" ]; then
            echo "App name = ${TARGET} already exists."
            exit 1
          fi
          echo "App name = ${TARGET} is available."
          EOF

      - name: create service account
        env:
          APP_NAME: ${{ inputs.app_name }}
        run: ssh "${{ secrets.INSTANCE_USER }}@${{ secrets.INSTANCE_HOST }}" "sudo useradd --system --home ${BASE_PATH}/${APP_NAME} --shell /usr/sbin/nologin svc_${APP_NAME}"

      - name: create source code folder
        env:
          APP_NAME: ${{ inputs.app_name }}
          SERVICE_ACCOUNT: svc_${{ inputs.app_name }}
        run: |
          ssh "${{ secrets.INSTANCE_USER }}@${{ secrets.INSTANCE_HOST }}" "bash -s" <<EOF
          set -euo pipefail
          APP_NAME="$APP_NAME"
          SERVICE_ACCOUNT="$SERVICE_ACCOUNT"
          BASE_PATH="${BASE_PATH}"
          sudo mkdir -p "${BASE_PATH}/${APP_NAME}/releases" "${BASE_PATH}/${APP_NAME}/current"
          sudo chown -R ${SERVICE_ACCOUNT}:appadmins "${BASE_PATH}/${APP_NAME}"
          sudo find "${BASE_PATH}/${APP_NAME}" -type d -exec chmod 750 {} \;
          sudo find "${BASE_PATH}/${APP_NAME}" -type f -exec chmod 640 {} \;
          sudo find "${BASE_PATH}/${APP_NAME}" -type d -exec chmod g+s {} \;
          EOF
